name: Pull request labeler

on:
  pull_request_target:
    types: [opened, reopened, closed]

jobs:
  label_pull_request:
    runs-on: ubuntu-24.04
   
    steps:
      - uses: actions/checkout@v7.0.0

      - name: echo
        run: echo Hello, world!
